#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Sep 03, 2024 11:22:51 AM +03  platform: Windows NT

import sys
import tkinter as tk
from tkinter.filedialog import askdirectory
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)


_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x300+639+236")
        top.minsize(120, 1)
        top.maxsize(4484, 1062)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.che52 = tk.IntVar()
        self.che63 = tk.IntVar()
        self.che58 = tk.IntVar()
        self.che53 = tk.IntVar()

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.867, rely=0.133, height=26, width=67)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(cursor="fleur")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Обзор''')
        self.Button1.configure(command=self.button_1_click)

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.05, rely=0.133, height=20, relwidth=0.79)
        self.Entry1.configure(background="white")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="#000000")
        self.Entry1.configure(insertbackground="#000000")
        self.Entry1.configure(selectbackground="#d9d9d9")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(validate='focusout')
        self.Entry1.configure(validatecommand=self.validate)

        self.Entry2 = tk.Entry(self.top)
        self.Entry2.place(relx=0.05, rely=0.31, height=20, relwidth=0.79)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="#000000")
        self.Entry2.configure(insertbackground="#000000")
        self.Entry2.configure(selectbackground="#d9d9d9")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(validate='focusout')
        self.Entry2.configure(validatecommand=self.validate)

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.867, rely=0.31, height=26, width=67)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''Обзор''')
        self.Button2.configure(command=self.button_2_click)

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.05, rely=0.243, height=14, width=104)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Выходная папка:''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.05, rely=0.067, height=14, width=94)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Путь к файлам:''')

        self.Checkbutton1 = tk.Checkbutton(self.top)
        self.Checkbutton1.place(relx=0.05, rely=0.433, relheight=0.057
                , relwidth=0.302)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="black")
        self.Checkbutton1.configure(anchor='w')
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(compound='left')
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="#000000")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Обрабатывать подпапки''')
        self.Checkbutton1.configure(variable=self.che52)

        self.Spinbox1 = tk.Spinbox(self.top, from_=50.0, to=100.0)
        self.Spinbox1.place(relx=0.167, rely=0.833, relheight=0.063
                , relwidth=0.075)
        self.Spinbox1.configure(activebackground="#d9d9d9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(foreground="#000000")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="#000000")
        self.Spinbox1.configure(insertbackground="#000000")
        self.Spinbox1.configure(selectbackground="#d9d9d9")
        self.Spinbox1.configure(selectforeground="black")

        self.Checkbutton4 = tk.Checkbutton(self.top)
        self.Checkbutton4.place(relx=0.05, rely=0.733, relheight=0.05
                , relwidth=0.435)
        self.Checkbutton4.configure(activebackground="#d9d9d9")
        self.Checkbutton4.configure(activeforeground="black")
        self.Checkbutton4.configure(anchor='w')
        self.Checkbutton4.configure(background="#d9d9d9")
        self.Checkbutton4.configure(compound='left')
        self.Checkbutton4.configure(cursor="fleur")
        self.Checkbutton4.configure(disabledforeground="#a3a3a3")
        self.Checkbutton4.configure(foreground="#000000")
        self.Checkbutton4.configure(highlightbackground="#d9d9d9")
        self.Checkbutton4.configure(highlightcolor="#000000")
        self.Checkbutton4.configure(justify='left')
        self.Checkbutton4.configure(text='''Использовать avif вместо heic''')
        self.Checkbutton4.configure(variable=self.che63)

        self.Checkbutton3 = tk.Checkbutton(self.top)
        self.Checkbutton3.place(relx=0.05, rely=0.633, relheight=0.057
                , relwidth=0.452)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="black")
        self.Checkbutton3.configure(anchor='w')
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(compound='left')
        self.Checkbutton3.configure(cursor="fleur")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="#000000")
        self.Checkbutton3.configure(justify='left')
        self.Checkbutton3.configure(text='''Копировать время создания/модификации''')
        self.Checkbutton3.configure(variable=self.che58)

        self.Checkbutton2 = tk.Checkbutton(self.top)
        self.Checkbutton2.place(relx=0.05, rely=0.533, relheight=0.057
                , relwidth=0.418)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(activeforeground="black")
        self.Checkbutton2.configure(anchor='w')
        self.Checkbutton2.configure(background="#d9d9d9")
        self.Checkbutton2.configure(compound='left')
        self.Checkbutton2.configure(cursor="fleur")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="#000000")
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''Сохранять структуру подпапок''')
        self.Checkbutton2.configure(variable=self.che53)

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.05, rely=0.833, height=21, width=64)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#000000")
        self.Label3.configure(text='''Качество''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.867, rely=0.833, height=26, width=67)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(cursor="fleur")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(state='disabled')
        self.Button3.configure(text='''Запуск''')

    def validate(self):
        if self.Entry1.get() and self.Entry2.get():
            self.Button3.configure(state='active')
            return True
        return False

    def on_invalid(self):
        self.Button3.configure(state='disabled')

    def button_1_click(self):
        self.set_entry_text(self.Entry1, askdirectory())

    def button_2_click(self):
        self.set_entry_text(self.Entry2, askdirectory())

    def set_entry_text(self, e: tk.Entry, text):
        e.delete(0, tk.END)
        e.insert(0, text)
        self.validate()



def start_up():
    ttk = Toplevel1(tk.Tk())
    ttk.top.mainloop()
    #unknown_support.main()

if __name__ == '__main__':
    ttk = Toplevel1(tk.Tk())
    ttk.top.mainloop()
    #unknown_support.main()




